### ISSUE TITLE
IWD Splash Page

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/josephine#9]
Collaborate with Stephanie on getting the IWD Splash page set up

**Comment by porteriffic** [comment]
Meet with Stephanie on 3/6 @ 11am

**Comment by cassininazir** [comment]
I'll join you both. Stephanie and I laid out the basic page at http://creativedisturbance.org/womensday.

**Comment by porteriffic** [comment]
@cassininazir Excellent. See you then
